name: Build & Push Docker Image(s)

on:
  push:
    branches:
      - main
    paths:
      - "auto-deploy"

jobs:
  docker:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"
          output-file: "false"
          git-user-name: ${{ github.repository_owner }}
          git-user-email: "${{ github.repository_owner }}@users.noreply.github.com"

      - name: Release
        if: ${{ steps.changelog.outputs.tag }}
        env:
          TAG: ${{ steps.changelog.outputs.tag }}
          MSG: ${{ steps.changelog.outputs.clean_changelog }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          assets=()
          for asset in auto-deploy; do
            assets+=("-a" "$asset")
          done
          echo -e "$TAG\n\n$MSG" | hub release create "${assets[@]}" -F- "$TAG"

      - uses: FranzDiebold/github-env-vars-action@v2
        if: ${{ steps.changelog.outputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ steps.changelog.outputs.tag }}

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
        if: ${{ steps.changelog.outputs.tag }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.CI_REPOSITORY_OWNER_SLUG }}/${{ env.CI_REPOSITORY_NAME_SLUG }}:${{ steps.changelog.outputs.tag }}
            ghcr.io/${{ env.CI_REPOSITORY_OWNER_SLUG }}/${{ env.CI_REPOSITORY_NAME_SLUG }}:latest
        if: ${{ steps.changelog.outputs.tag }}
